name: storymate
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6 # GetX 라이브러리 추가
  flutter_svg: ^2.0.17 # svg 이미지 적용을 위한 라이브러리
  intl: ^0.20.2 # DateTime -> 문자열 변환을 위함
  flutter_native_splash: ^2.4.4 # 스플래쉬 스크린
  flutter_dotenv: ^5.2.1
  kakao_flutter_sdk: ^1.9.6
  web_socket_channel: ^3.0.2
  package_info_plus: ^8.2.1
  dio: ^5.3.2
  shared_preferences: ^2.0.11
  http: ^1.0.0
  flutter_screenutil: ^5.9.3 # 반응형
  highlightable_text: ^0.0.1 # 하이라이트 기능
  tosspayments_widget_sdk_flutter: ^2.1.0 # 토스 페이먼츠

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Jua
      fonts:
        - asset: assets/fonts/BMJUA_ttf.ttf
    - family: Nanum
      fonts:
        - asset: assets/fonts/NanumGothic.ttf
  assets:
    - assets/
    - assets/books/
    - assets/kim_cheomji.png
    - assets/mermaid.png
    - assets/TheLittleGirl.png
    - assets/SimCheong.png
    - assets/mermaid2.png
    - assets/Dongbaekkkot.png
    - assets/mouse.png
    - assets/duck.png
    - assets/theBuckwheatFlower.png
    - assets/HongGildong.png
    - .env

# 스플래쉬 화면 설정
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    icon_background_color: "#FFFFFF"
